# Generated by Django 3.1.7 on 2021-06-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210608_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_ID',
            field=models.CharField(default=1623342470.446694, max_length=256, null=True),
        ),
    ]
