# Generated by Django 3.1.7 on 2021-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210610_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_ID',
            field=models.CharField(default=1623346932.874129, max_length=256, null=True),
        ),
    ]
